version: '3.7'
services:
  # 1. The Engine (Redpanda)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v22.3.11
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"

  # 2. The Dashboard
  console:
    image: redpandadata/console:v2.2.3
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092
    depends_on:
      - redpanda

  # 3. YOUR PYTHON SCRIPT (The Producer)
  producer:
    build: .
    container_name: crypto-producer
    depends_on:
      - redpanda
  # 4. The Dashboard (Streamlit)
  dashboard:
    build: .
    container_name: crypto-dashboard
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    depends_on:
      - redpanda
      - producer